- name: Facts Demo
  hosts: servera*
  gather_facts: false
  tasks:
    - name: Collect limited Hardware facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'min'
          - 'network'
          - 'hardware'
    - name: Print the Facts
      ansible.builtin.copy:
        dest: /tmp/info.txt
        content: |
          Arch2         = {{ ansible_architecture }}
          Date          = {{ ansible_date_time['date'] }}
          Time          = {{ ansible_date_time['time'] }}
          IP Address    = {{ ansible_default_ipv4['address'] }}
          OS            = {{ ansible_facts['distribution'] }}
          FQDN          = {{ ansible_fqdn }}
          Hostname      = {{ ansible_hostname }}
          Total Memory  = {{ ansible_memory_mb.real.total }}
      when: ansible_distribution_version == "9.0"

    - name: Collect Package Facts
      ansible.builtin.package_facts:
      
    - name: Print Package Facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages.httpd[0].version }}"

    - name: Collect Service Facts
      ansible.builtin.service_facts:
      
    - name: Print Service Facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts['services']['httpd.service']['state'] }}"
