- name: Tags Demo (Run Selected Tasks)
  hosts: servera*
  gather_facts: false
  tasks:
  - name: Task 1 in Development
    ansible.builtin.debug:
      msg: "Task 1 for Development"
    tags:
      # - all
      - dev
      - windows

  - name: Task 1 in Production
    ansible.builtin.debug:
      msg: "Task 1 for Production"
    tags:
      - prod

  - name: Task which run ALWAYS
    ansible.builtin.debug:
      msg: "I am going to run always"
    tags:
      - always

  - name: No Tag here please
    ansible.builtin.debug:
      msg: "Untagged with precious metal"

  - name: Destroy the Datacenter
    ansible.builtin.debug:
      msg: "Emergency get out of here"
    tags:
      - never

  - name: Task 2 in Development
    ansible.builtin.debug:
      msg: "Task 2 for Development"
    tags:
      - dev

  - name: Task 2 in Production
    ansible.builtin.debug:
      msg: "Task 2 for Production"
    tags:
      - prod
