- name: Tower Machine Credentials Role Playbook
  hosts: localhost
  gather_facts: no

  tasks:

  - name: Add credential "Operations"
    ansible.controller.credential:
      name: "Operations"
      description: "Operations Credential"
      organization: "Default"
      inputs:
        username: "devops"
        password: "redhat"
        become_method: "sudo"
        become_username: "root"
        become_password: "redhat"
      credential_type: "Machine"
      state: "present"
      controller_config_file: "./controller_cli.cfg"

  #- name: Add credential via command Line
  #  shell: >
  #          tower-cli credential create
  #          --name "Operations" --organization "Default" 
  #          --description "Operations Credential" --credential-type "Machine"
  #          --tower-host "tower.lab.example.com" --tower-username "admin"
  #          --tower-password "redhat" --insecure
            

   
  - name: Assign permissions (role) to Operations Team
    ansible.controller.role:
      credential: "Operations"
      team: "Operations"
      role: "admin"
      state: "present"
      controller_config_file: "./controller_cli.cfg"
      #tower_host: "tower.lab.example.com"
      #tower_username: "admin"
      #tower_password: "redhat"
      #validate_certs: false


  - name: Assign permissions (role) to Developers Team
    ansible.controller.role:  
      credential: "Operations"
      team: "Developers"
      role: "use"   
      state: "present"
      controller_config_file: "./controller_cli.cfg"

  #- name: Assign permissions (role) to Developers Team
  #  shell: > 
  #          tower-cli role grant 
  #          --team 'Developers' --credential "Operations" --type 'use'
  #          --tower-host "tower.lab.example.com" --tower-username "admin" 
  #          --tower-password "redhat" --insecure
