namespace: traffic
name: rail

version: 1.0.0
readme: README.md

authors:
- Daniel 2<daniel2@redhat.com>

description: Traffic Rail collection

license:
- GPL-2.0-or-later
license_file: ''

tags: []

dependencies:
  community.general: '>=1.0.0'
  ansible.posix: '>=1.0.0'

repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore: []
