- name: Guided Exercise -- Creating Machine Credentials for Access to Inventory Hosts
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Add controller inventory
    ansible.controller.inventory:
      name: "Dev"
      description: "Development Inventory"
      organization: "Default"
      state: "present"
      controller_config_file: "./controller_cli.cfg"


  - name: Add controller group's
    ansible.controller.group:
      name: "dev_servers"
      description: "Development servers"
      inventory: "Dev"
      state: "present"
      controller_config_file: "./controller_cli.cfg"
    register: inventory_groups_output

####  Print Group information created earlier, as it will be
####  used later
 
  - name: Print group's information
    debug:
      var: inventory_groups_output
   
  - name: Add controller host with "admin" user rights
    ansible.controller.host:
      name: "{{ item.server_name }}"
      description: "{{ item.server_description }}"
      inventory: "Dev"
      state: "present"
      controller_config_file: "./controller_cli.cfg"
    loop:
    - server_name: "servera.lab.example.com"
      server_description: "Server A"
    - server_name: "serverb.lab.example.com"
      server_description: "Server B"
    register: inventory_hosts_output

  - name: Print Hosts Information
    debug:
      var: inventory_hosts_output

  - name: Associate 'servera/b.lab.example.com' Host to Group 'dev_servers'
    ansible.controller.group:
      name: dev_servers
      inventory: Dev
      state: present
      controller_config_file: "./controller_cli.cfg"
      hosts:
      - servera.lab.example.com
      - serverb.lab.example.com



  - name: Add admin role to Developers team via controller_role
    ansible.controller.role:
      inventory: "Dev"
      team: "Developers"
      role: "admin"
      state: "present"
      controller_config_file: "./controller_cli.cfg"

  - name: Add credential "Developers"
    ansible.controller.credential:
      name: "Developers"
      description: "Developers Credential"
      organization: "Default"
      inputs:
        username: "devops"
        password: "redhat"
        become_method: "sudo"
        become_username: "root"
        become_password: "redhat"
      credential_type: "Machine"
      state: "present"
      controller_config_file: "./controller_cli.cfg"

  - name: Add admin role to Developers team via controller_role
    ansible.controller.role:
      credential: "Developers"
      team: "Developers"
      role: "admin"
      state: "present"
      controller_config_file: "./controller_cli.cfg"
